// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyeajJ_DdLoppO1cU8lng6cMAHJwvhCqg',
    appId: '1:1039182789055:web:7784ab2c12548e3777490a',
    messagingSenderId: '1039182789055',
    projectId: 'piscineintelligente',
    authDomain: 'piscineintelligente.firebaseapp.com',
    storageBucket: 'piscineintelligente.firebasestorage.app',
    measurementId: 'G-58W1H9W1W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1pLss-MbSJfMNrUDprXfejFbiz6bawI',
    appId: '1:1039182789055:android:de775c0ad04b668e77490a',
    messagingSenderId: '1039182789055',
    projectId: 'piscineintelligente',
    storageBucket: 'piscineintelligente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuYBuRwXybwlXGlgZ2gYUQfYpmtDbhpTk',
    appId: '1:1039182789055:ios:b21bcfc85ac72a0877490a',
    messagingSenderId: '1039182789055',
    projectId: 'piscineintelligente',
    storageBucket: 'piscineintelligente.firebasestorage.app',
    iosBundleId: 'com.example.piscineIntelligente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuYBuRwXybwlXGlgZ2gYUQfYpmtDbhpTk',
    appId: '1:1039182789055:ios:b21bcfc85ac72a0877490a',
    messagingSenderId: '1039182789055',
    projectId: 'piscineintelligente',
    storageBucket: 'piscineintelligente.firebasestorage.app',
    iosBundleId: 'com.example.piscineIntelligente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyeajJ_DdLoppO1cU8lng6cMAHJwvhCqg',
    appId: '1:1039182789055:web:56c2c89fe4be7f5477490a',
    messagingSenderId: '1039182789055',
    projectId: 'piscineintelligente',
    authDomain: 'piscineintelligente.firebaseapp.com',
    storageBucket: 'piscineintelligente.firebasestorage.app',
    measurementId: 'G-44B4VRLTC9',
  );

}