name: Simple Flutter Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: build/web
        retention-days: 30